global using System.ComponentModel.DataAnnotations;
global using DragonsDogma2FileBackupWorker.Logic;
global using DragonsDogma2FileBackupWorker.Logic.Abstract;
global using DragonsDogma2FileBackupWorker.Logic.IO.Abstract;
global using DragonsDogma2FileBackupWorker.Models;
global using DragonsDogma2FileBackupWorker.Models.Abstract;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Moq;
global using NUnit.Framework;
global using BackupManager = DragonsDogma2FileBackupWorker.Logic.BackupManager;